version: '3.1'
services:
  syntaxnet:
    image: ljm625/syntaxnet-rest-api:dragnn
    ports:
      - "9000:9000"
    volumes:
      - ./syntaxnet/models:/models
#  db:
#    build: db/.
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpass
#      MYSQL_ROOT_PASSWORD: mypassword
#      MYSQL_USER: dbuser
#      MYSQL_PASSWORD: userpass
#      MYSQL_DATABASE: hophacks
  stream_api:
    build:
      context: ./src/fake_news
      dockerfile: stream.dockerfile
    ports:
      - "8001:8001"
    restart: always

  nginx:
    build: ./proxy/.
    ports:
       - "443:443"
       - "80:80"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - stream_api