version: '3.1'
services:
  syntaxnet:
    image: ljm625/syntaxnet-rest-api:dragnn
    ports:
      - "9000:9000"
    volumes:
      - ./ssyntaxnet/models:/models
#  db:
#    build: db/.
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpass
#      MYSQL_ROOT_PASSWORD: mypassword
#      MYSQL_USER: dbuser
#      MYSQL_PASSWORD: userpass
#      MYSQL_DATABASE: hophacks
  stream_api:
    build:
      context: .
      dockerfile: stream.dockerfile
    ports:
      - "8001:8001"